/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPUTER
 */
public class CardDriver extends javax.swing.JPanel {
    private int id_driver;
    private dbConnect db;
    private String path;
    
    /**
     * Creates new form CardDriver
     */
    public CardDriver(int id, String name, String number, String team, String principal, String path) {
        initComponents();
        // koneksi ke database
        db = new dbConnect();
        // set id driver
        this.id_driver = id;
        // set img path
        this.path = path;
        // set label
        driverName.setText(name);
        driverNumber.setText(number);
        driverTeam.setText(team);
        teamPrincipal.setText(principal);
        // set img
        setImg(path);
    }
    // method untuk set image
    public void setImg(String path) {
        // buat imageicon dari path
        ImageIcon i = new ImageIcon("DriverImg/" + path);
        // atur ukuran image
        Image img = i.getImage().getScaledInstance(106, 147, Image.SCALE_SMOOTH);
        // set image
        imgLabel.setIcon(new ImageIcon(img));
    }
    // method untuk memanggil method setMenu dari MainMenu wkwk
    public void refreshPanel() {
        MainMenu parent = (MainMenu) this.getTopLevelAncestor();
        
        if (parent != null) parent.setPanel();
    }
    // method untuk menghapus data dari database
    public void deleteData() {
        // confirm message
        // jika user menekan 'yes'
        if (JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Warning", JOptionPane.YES_NO_OPTION) == 0) {
            // Remove Data from database
            String sql = "DELETE FROM drivers WHERE id_driver = '"+id_driver+"'";
            db.updateQuery(sql);
            // Show Information
            System.out.println("Data Berhasil Dihapus");
            refreshPanel();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverImg = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        driverName = new javax.swing.JLabel();
        driverNumber = new javax.swing.JLabel();
        driverTeam = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        teamPrincipal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(32767, 165));
        setPreferredSize(new java.awt.Dimension(422, 161));

        javax.swing.GroupLayout driverImgLayout = new javax.swing.GroupLayout(driverImg);
        driverImg.setLayout(driverImgLayout);
        driverImgLayout.setHorizontalGroup(
            driverImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        driverImgLayout.setVerticalGroup(
            driverImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverImgLayout.createSequentialGroup()
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Outfit", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Driver Name");

        jLabel2.setFont(new java.awt.Font("Outfit", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Driver Number");

        jLabel3.setFont(new java.awt.Font("Outfit", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Team");

        driverName.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        driverName.setForeground(new java.awt.Color(0, 0, 0));
        driverName.setText("jLabel4");

        driverNumber.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        driverNumber.setForeground(new java.awt.Color(0, 0, 0));
        driverNumber.setText("jLabel4");

        driverTeam.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        driverTeam.setForeground(new java.awt.Color(0, 0, 0));
        driverTeam.setText("jLabel4");

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Outfit", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Team Principals");

        teamPrincipal.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        teamPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        teamPrincipal.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(driverName, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(driverTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driverNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teamPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(driverImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(driverName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(driverNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(driverTeam))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(teamPrincipal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // button delete, lupa ganti nama d design nya hehe
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_jButton2ActionPerformed
    // button update
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // buat & munculkan objek FormUpdate
        FormUpdate f = new FormUpdate(id_driver, driverName.getText(), driverNumber.getText(), this.path);
        f.setVisible(true);
        // set parent nya which is MainMenu
        MainMenu parent = (MainMenu) this.getTopLevelAncestor();
        // ilangin tombol biar ga d spam mulu
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        
        f.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (parent != null) parent.setPanel();
            }
        });
        jButton1.setVisible(true);
        jButton2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel driverImg;
    private javax.swing.JLabel driverName;
    private javax.swing.JLabel driverNumber;
    private javax.swing.JLabel driverTeam;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel teamPrincipal;
    // End of variables declaration//GEN-END:variables
}
