/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author COMPUTER
 */
public class MainMenu extends javax.swing.JFrame {
    // attribut untuk koneksi ke database dan id dari id user
    private dbConnect db;
    private int id;
    /**
     * Creates new form MainMenu
     */
    public MainMenu(int id) {
        initComponents();
        // koneksi ke database
        db = new dbConnect();
        // set id
        this.id = id;
        // set panel
        setPanel();
    }
    // method untuk set panel menampilkan data driver
    public void setPanel() {
        // hapus dlu yg ada
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        // query untuk mendapatkan data driver f1 sesuai dengan id user yang telah login
        ResultSet res = db.selectQuery("SELECT id_driver, name, number, team_name, team_principal, driver_img" +
        " FROM ((drivers JOIN akun ON drivers.id_user = '"+id+"')" +
        " JOIN teams ON drivers.id_team = teams.id_team)");
        
        try{
            // selama data nya masih ada
            while (res.next()) {
                // buat card baru dengan data dari database
               mainPanel.add(new CardDriver(res.getInt("id_driver"), res.getString("name"), 
                       res.getString("number"), res.getString("team_name"), 
                       res.getString("team_principal"), res.getString("driver_img")));
           }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    // set panel tapi buat data nya dari tabel teams
    public void setPanelTeam() {
        mainPanel.removeAll();
        mainPanel.setLayout(new GridLayout(0, 1));
        // query untuk mendapatkan data tean f1
        ResultSet res = db.selectQuery("SELECT id_team, team_name, team_principal FROM teams");
        
        try{
            // selama data nya masih ada
            while (res.next()) {
                // buat card baru
               mainPanel.add(new CardTeam(res.getInt("id_team"), res.getString("team_name"), res.getString("team_principal")));
           }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addDriverButton = new javax.swing.JButton();
        ScrollPanel = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        addTeamButton = new javax.swing.JButton();
        DriverListButton = new javax.swing.JButton();
        TeamListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Outfit ExtraBold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("F1 Grid Data");

        addDriverButton.setBackground(new java.awt.Color(102, 255, 255));
        addDriverButton.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        addDriverButton.setForeground(new java.awt.Color(0, 0, 0));
        addDriverButton.setText("Add Driver");
        addDriverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverButtonActionPerformed(evt);
            }
        });

        ScrollPanel.setBackground(new java.awt.Color(255, 102, 51));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        ScrollPanel.setViewportView(mainPanel);

        addTeamButton.setBackground(new java.awt.Color(102, 255, 255));
        addTeamButton.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        addTeamButton.setForeground(new java.awt.Color(0, 0, 0));
        addTeamButton.setText("Add Team");
        addTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamButtonActionPerformed(evt);
            }
        });

        DriverListButton.setBackground(new java.awt.Color(255, 0, 0));
        DriverListButton.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        DriverListButton.setText("Driver List");
        DriverListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverListButtonActionPerformed(evt);
            }
        });

        TeamListButton.setBackground(new java.awt.Color(255, 0, 0));
        TeamListButton.setFont(new java.awt.Font("Outfit", 1, 12)); // NOI18N
        TeamListButton.setText("Team List");
        TeamListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDriverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DriverListButton)
                .addGap(18, 18, 18)
                .addComponent(TeamListButton)
                .addGap(182, 182, 182))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDriverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addTeamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DriverListButton)
                            .addComponent(TeamListButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverButtonActionPerformed
        // TODO add your handling code here:
        // hide button
        addDriverButton.setVisible(false);
        addTeamButton.setVisible(false);
        // pindah ke page form
        FormAdd a = new FormAdd(this.id);
        a.setVisible(true);
        // ketika window FormAdd nya d tutup, refresh panel
        a.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Call setPanel() after the FormAdd frame is disposed/closed
                setPanel();
                addDriverButton.setVisible(true);
                addTeamButton.setVisible(true);
            }
        });
    }//GEN-LAST:event_addDriverButtonActionPerformed

    private void addTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamButtonActionPerformed
        // TODO add your handling code here:
        // hide button
        addTeamButton.setVisible(false);
        addTeamButton.setVisible(false);
        // pindah ke page add team
        FormAddTeam a = new FormAddTeam();
        a.setVisible(true);
        // ketika page nya d tutup, refresh panel nya
        a.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Call setPanel() after the FormAdd frame is disposed/closed
                setPanel();
                addTeamButton.setVisible(true);
                addTeamButton.setVisible(true);
            }
        });
    }//GEN-LAST:event_addTeamButtonActionPerformed

    private void DriverListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverListButtonActionPerformed
        // TODO add your handling code here:
        setPanel();
    }//GEN-LAST:event_DriverListButtonActionPerformed

    private void TeamListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamListButtonActionPerformed
        // TODO add your handling code here:
        setPanelTeam();
    }//GEN-LAST:event_TeamListButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DriverListButton;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JButton TeamListButton;
    private javax.swing.JButton addDriverButton;
    private javax.swing.JButton addTeamButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
